// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbRrS7j3AMsB-kRBUtWKDGBfNbbtfTNzY',
    appId: '1:815093605620:android:9c46729d93742fca082aa1',
    messagingSenderId: '815093605620',
    projectId: 'uniwave-788ba',
    authDomain: '',
    storageBucket: 'uniwave-788ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRrS7j3AMsB-kRBUtWKDGBfNbbtfTNzY',
    appId: '1:815093605620:android:9c46729d93742fca082aa1',
    messagingSenderId: '815093605620',
    projectId: 'uniwave-788ba',
    storageBucket: 'uniwave-788ba.appspot.com',
  );
}
